### PR TITLE
enable metadata to be got and set

### PR DESCRIPTION
**Pull request by thommay**
Signed-off-by: Thom May <thom@chef.io>

### CODE REVIEW

**Comment by robbkidd** [comment]
The changes make sense. Is the `reset!` behavior worthy of some direct specs?

**Comment by thommay** [comment]
> Is the reset! behavior worthy of some direct specs?

I'm 99% sure that it's only used in tests.

**Comment by robbkidd** [comment]
> I'm 99% sure that it's only used in tests.

Fair enough.

**Comment by thommay** [comment]
> I'm 99% sure that it's only used in tests.

That comment was so inaccurate i've deleted it. But I'm not sure that there's value in testing it.

**Pull request merged**
