### PR TITLE
RuboCop lint rules, linting, TODO config added

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds a RuboCop configuration file with quite few excludes and such.

- lines in this projects are wider
- double quotes are double
- the `features/` directory has code generated by Cucumber, so I excluded it

This all makes us compatible with chefstyle 0.6.0.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Now, in order to reach "DCO" status, I'd need to re-do these commits.

Would a squash into a single commit be too dramatic?

**Comment by olleolleolle** [comment]
I filed this PR to `rake`, to get around the issue that it exposes its own `.rubocop.yml` in its downloaded files: https://github.com/ruby/rake/pull/217

This is fixed by us not including `vendor/` in the scope of files to check.

**Comment by tas50** [comment]
@olleolleolle Any reason to not just use Chefstyle with the stock config like we're doing elsewhere?

**Comment by olleolleolle** [comment]
@tas50 _Oh_, I _learned_ about Chefstyle while doing this change. But I failed to realize _how_ much it takes care of.

(The first thing I did was to run `rubocop`, which failed, and so on. And, then incrementally, I took steps to make things work more and more. At the end, I saw that the Travis CI script (Rake default task) had a `style` task, so I began using that, even asking it to do "-a" for auto-correct.)

Gah.

So, can I close this with no change?

**Comment by olleolleolle** [comment]
Closing this with no change.

**Pull request closed without merging**
